services:
  mysql:
    image: mysql:latest
    container_name: hng-task-2-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: